// Generated by scripts/generate_power2_candidate_identity.py.
// Edit products/power/candidate.json and regenerate. Do not compile this
// candidate identity into a public App release.

enum Power2CandidateIdentity {
    static let stackID = "power-text-iphone-2.0.0-rc.1"
    static let measurementStackPath = "products/power/stacks/power-text-iphone-2.0.0-rc.1/manifest.json"
    static let measurementStackSHA256 = "a92a208324af0ea85c092e1cf04248c669f01c588c9f0d0b724e4c40a1014642"
    static let runnerCandidateManifestPath = "apps/PowerRunnerKit/component-manifest.json"
    static let runnerCandidateManifestSHA256 = "87f62feecc2b3fca994cc4f40214aed9876f1477c51fdb7c56c6945eb6b03ee2"
    static let publicIntakeOpen = false
    // Enables the closed Official measurement rehearsal.
    static let appReleaseAvailable = true
    // Lets this exact candidate create a real result-only pull request while
    // trusted repository CI remains authoritative and public intake is closed.
    static let submissionRehearsalAvailable = true
}
