// Generated by scripts/generate_power2_product_identity.py.
// Edit the Power product pointer and regenerate. Intake state is intentionally
// not embedded; trusted repository CI remains authoritative.

enum Power2ProductIdentity {
    static let stackID = "power-text-iphone-2.0.0-rc.1"
    static let measurementStackPath = "products/power/stacks/power-text-iphone-2.0.0-rc.1/manifest.json"
    static let measurementStackSHA256 = "a92a208324af0ea85c092e1cf04248c669f01c588c9f0d0b724e4c40a1014642"
    static let runnerComponentsManifestPath = "apps/PowerRunnerKit/component-manifest.json"
    static let runnerComponentsManifestSHA256 = "87f62feecc2b3fca994cc4f40214aed9876f1477c51fdb7c56c6945eb6b03ee2"
    // A release candidate may be rehearsed before trusted public intake opens.
    // Repository validation decides whether any produced result is accepted.
    static let appReleaseAvailable = true
}
