#!/usr/bin/env python3
"""Generate Xcode settings from the one Power 2 App build identity."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
IDENTITY_PATH = ROOT / "apps/ios/Configuration/ReleaseIdentity.json"
OUTPUT_PATH = (
    ROOT / "apps/ios/Configuration/ReleaseIdentity.generated.xcconfig"
)
SCHEMA_VERSION = "power-app-build-identity-1.0.0-draft.1"
SEMVER_PATTERN = re.compile(
    r"^[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?$"
)
BUNDLE_PATTERN = re.compile(
    r"^[A-Za-z0-9][A-Za-z0-9.-]*[A-Za-z0-9]$"
)
BUILD_KINDS = ("developer", "certification", "official")


def _string(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{field} must be a non-empty string")
    return value


def load_identity() -> dict[str, Any]:
    value = json.loads(IDENTITY_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("App release identity must be a JSON object")
    if value.get("schemaVersion") != SCHEMA_VERSION:
        raise ValueError("unsupported App release identity schema")

    version = _string(value.get("version"), "version")
    build = _string(value.get("build"), "build")
    if SEMVER_PATTERN.fullmatch(version) is None:
        raise ValueError("version must be a semantic version")
    if not build.isdigit() or int(build) < 1:
        raise ValueError("build must be a positive integer string")

    kinds = value.get("buildKinds")
    if not isinstance(kinds, dict) or set(kinds) != set(BUILD_KINDS):
        raise ValueError(
            "buildKinds must contain developer, certification, and official"
        )
    bundle_identifiers: set[str] = set()
    display_names: set[str] = set()
    for kind in BUILD_KINDS:
        identity = kinds.get(kind)
        if not isinstance(identity, dict):
            raise ValueError(f"buildKinds.{kind} must be an object")
        bundle = _string(
            identity.get("bundleIdentifier"),
            f"buildKinds.{kind}.bundleIdentifier",
        )
        display = _string(
            identity.get("displayName"),
            f"buildKinds.{kind}.displayName",
        )
        if BUNDLE_PATTERN.fullmatch(bundle) is None:
            raise ValueError(
                f"buildKinds.{kind}.bundleIdentifier is invalid"
            )
        if bundle in bundle_identifiers:
            raise ValueError("every build kind requires a distinct Bundle ID")
        if display in display_names:
            raise ValueError(
                "every build kind requires a distinct display name"
            )
        bundle_identifiers.add(bundle)
        display_names.add(display)
    return value


def render_xcconfig(identity: dict[str, Any]) -> str:
    kinds = identity["buildKinds"]
    lines = [
        "// Generated by scripts/generate_power_app_release_identity.py.",
        "// Edit ReleaseIdentity.json and regenerate; do not edit this file.",
        f"POWER_APP_MARKETING_VERSION = {identity['version']}",
        f"POWER_APP_BUILD_NUMBER = {identity['build']}",
        "MARKETING_VERSION = $(POWER_APP_MARKETING_VERSION)",
        "CURRENT_PROJECT_VERSION = $(POWER_APP_BUILD_NUMBER)",
    ]
    for kind in BUILD_KINDS:
        prefix = f"POWER_APP_{kind.upper()}"
        lines.extend(
            (
                f"{prefix}_BUNDLE_IDENTIFIER = "
                f"{kinds[kind]['bundleIdentifier']}",
                f"{prefix}_DISPLAY_NAME = {kinds[kind]['displayName']}",
            )
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of rewriting a stale generated configuration",
    )
    args = parser.parse_args(argv)
    try:
        expected = render_xcconfig(load_identity())
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.check:
        try:
            actual = OUTPUT_PATH.read_text(encoding="utf-8")
        except OSError:
            actual = ""
        if actual != expected:
            print(
                "error: apps/ios/Configuration/"
                "ReleaseIdentity.generated.xcconfig is stale",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
