#!/usr/bin/env python3
"""Generate the Swift identity for the exact Power MLX dependency lock."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = ROOT / "apps/PowerRunnerKit/Package.resolved"
RUNTIME_IDENTITY_PATH = ROOT / "apps/PowerRunnerKit/runtime-identity.json"
LOCK_OUTPUT_PATH = (
    ROOT
    / "apps/PowerRunnerKit/Sources/PowerMLXRuntime"
    / "PowerMLXDependencyLock.generated.swift"
)
RUNTIME_OUTPUT_PATH = (
    ROOT
    / "apps/PowerRunnerKit/Sources/PowerMLXRuntime"
    / "PowerMLXRuntimeIdentity.swift"
)
REQUIRED_DIRECT_PINS = {
    "mlx-swift": (
        "0.31.6",
        "0bb916c67f4b9e5c682cbe02a42c701c93ab5021",
    ),
    "mlx-swift-lm": (
        "3.31.4",
        "bd4b7434e6bdb588c7ef55706ff8904cb7fd4c57",
    ),
    "swift-huggingface": (
        "0.9.0",
        "b721959445b617d0bf03910b2b4aced345fd93bf",
    ),
    "swift-transformers": (
        "1.3.0",
        "b38443e44d93eca770f2eb68e2a4d0fa100f9aa2",
    ),
}


def _load_runtime_identity() -> dict:
    value = json.loads(RUNTIME_IDENTITY_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("runtime identity must be a JSON object")
    required = {
        "schemaVersion",
        "name",
        "version",
        "resolvedRevision",
        "backend",
        "configuration",
    }
    if set(value) != required:
        raise ValueError("runtime identity field set is invalid")
    if (
        value["schemaVersion"]
        != "power-runtime-identity-1.0.0-draft.1"
        or not isinstance(value["configuration"], dict)
    ):
        raise ValueError("runtime identity schema is unsupported")
    return value


def _verified_lock_digest(runtime: dict) -> str:
    lock_bytes = LOCK_PATH.read_bytes()
    document = json.loads(lock_bytes)
    pins = {
        pin["identity"]: (
            pin["state"].get("version"),
            pin["state"]["revision"],
        )
        for pin in document.get("pins", [])
    }
    for identity, expected in REQUIRED_DIRECT_PINS.items():
        if pins.get(identity) != expected:
            raise ValueError(
                f"{identity} resolved to {pins.get(identity)!r}, "
                f"expected {expected!r}"
            )
    digest = hashlib.sha256(lock_bytes).hexdigest()
    if runtime["configuration"].get("dependencyLockSHA256") != digest:
        raise ValueError(
            "runtime identity dependency lock digest is stale"
        )
    return digest


def render_lock(runtime: dict) -> str:
    digest = _verified_lock_digest(runtime)
    return f"""// Generated by scripts/generate_power_mlx_dependency_identity.py.
// Do not edit by hand.

enum PowerMLXDependencyLock {{
    static let sha256 = "{digest}"
}}
"""


def _swift_string(value: str) -> str:
    return json.dumps(value)


def _swift_json_value(value: object) -> str:
    if isinstance(value, bool):
        return f".boolean({str(value).lower()})"
    if isinstance(value, str):
        return f".string({_swift_string(value)})"
    raise ValueError("runtime configuration contains an unsupported value")


def render_runtime(runtime: dict) -> str:
    _verified_lock_digest(runtime)
    configuration = runtime["configuration"]
    entries = ",\n".join(
        "                "
        + f"{_swift_string(key)}: {_swift_json_value(value)}"
        for key, value in sorted(configuration.items())
    )
    return f"""// Generated by scripts/generate_power_mlx_dependency_identity.py.
// Edit apps/PowerRunnerKit/runtime-identity.json and regenerate.

import Foundation
import PowerEvidence
import PowerRunnerCore

public enum PowerMLXRuntimeIdentity {{
    public static let name = {_swift_string(runtime["name"])}
    public static let version = {_swift_string(runtime["version"])}
    public static let resolvedRevision =
        {_swift_string(runtime["resolvedRevision"])}
    public static let backend = {_swift_string(runtime["backend"])}

    public static var evidence: PowerEvidence.PowerRuntimeIdentity {{
        .init(
            name: name,
            version: version,
            resolvedRevision: resolvedRevision,
            backend: backend,
            configuration: [
{entries}
            ]
        )
    }}
}}

public enum PowerMLXRuntimeError: Error, LocalizedError, Sendable {{
    case unsupportedInferenceConfiguration
    case missingCompletionInformation
    case outputTokenCountMismatch(expected: Int, observed: Int)
    case invalidArtifactIdentity

    public var errorDescription: String? {{
        switch self {{
        case .unsupportedInferenceConfiguration:
            "The Power workload requested an unsupported MLX inference configuration."
        case .missingCompletionInformation:
            "MLX generation ended without completion information."
        case .outputTokenCountMismatch(let expected, let observed):
            "MLX reported \\(expected) output tokens but emitted \\(observed)."
        case .invalidArtifactIdentity:
            "The model artifact ID or immutable revision is invalid."
        }}
    }}
}}

extension PowerMLXRuntimeError: PowerRuntimeFailureClassifyingError {{
    public var powerRuntimeFailureKind: PowerRuntimeFailureKind {{
        switch self {{
        case .unsupportedInferenceConfiguration:
            .failed(code: "mlx_unsupported_inference_configuration")
        case .missingCompletionInformation:
            .failed(code: "mlx_missing_completion_information")
        case .outputTokenCountMismatch:
            .failed(code: "mlx_output_token_count_mismatch")
        case .invalidArtifactIdentity:
            .failed(code: "mlx_invalid_artifact_identity")
        }}
    }}
}}

enum PowerMLXRuntimeContract {{
    static func validate(
        _ configuration: PowerInferenceConfiguration
    ) throws {{
        guard
            !configuration.sampling,
            configuration.temperature == 0,
            configuration.topP == 1,
            configuration.topK == 0,
            configuration.seed >= 0,
            configuration.maximumOutputTokens > 0,
            configuration.maximumOutputTokens <= 512,
            configuration.reasoningMode == "disabled",
            configuration.newContextPerAttempt,
            configuration.newKVCachePerAttempt
        else {{
            throw PowerMLXRuntimeError
                .unsupportedInferenceConfiguration
        }}
    }}
}}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of rewriting stale generated Swift",
    )
    args = parser.parse_args(argv)
    try:
        runtime = _load_runtime_identity()
        expected_lock = render_lock(runtime)
        expected_runtime = render_runtime(runtime)
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    if args.check:
        actual_lock = (
            LOCK_OUTPUT_PATH.read_text(encoding="utf-8")
            if LOCK_OUTPUT_PATH.exists()
            else ""
        )
        actual_runtime = (
            RUNTIME_OUTPUT_PATH.read_text(encoding="utf-8")
            if RUNTIME_OUTPUT_PATH.exists()
            else ""
        )
        if (
            actual_lock != expected_lock
            or actual_runtime != expected_runtime
        ):
            print(
                "error: generated Power MLX runtime identity is stale",
                file=sys.stderr,
            )
            return 1
        return 0
    LOCK_OUTPUT_PATH.write_text(expected_lock, encoding="utf-8")
    RUNTIME_OUTPUT_PATH.write_text(expected_runtime, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
