#!/usr/bin/env python3
"""Generate candidate-only Swift identity from the Power 2 candidate pointer."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CANDIDATE_PATH = ROOT / "products/power/candidate.json"
OUTPUT_PATH = ROOT / "apps/ios/Power2CandidateIdentity.generated.swift"


def _string(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{field} must be a non-empty string")
    return value


def _reference(value: Any, field: str) -> dict[str, str]:
    if not isinstance(value, dict):
        raise ValueError(f"{field} must be an object")
    path = _string(value.get("path"), f"{field}.path")
    digest = _string(value.get("sha256"), f"{field}.sha256")
    if len(digest) != 64 or any(
        character not in "0123456789abcdef" for character in digest
    ):
        raise ValueError(f"{field}.sha256 must be a lowercase SHA-256")
    return {"path": path, "sha256": digest}


def load_candidate() -> dict[str, Any]:
    value = json.loads(CANDIDATE_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("Power candidate must be a JSON object")
    if value.get("schemaVersion") != "power-stack-pointer-1.0.0-draft.1":
        raise ValueError("unsupported Power candidate schema")
    if value.get("status") != "migration-draft":
        raise ValueError("generated identity accepts migration drafts only")
    if value.get("publicIntakeOpen") is not False:
        raise ValueError("candidate identity cannot open public intake")
    if value.get("appRelease") is not None:
        raise ValueError("candidate App release must remain null")
    _string(value.get("stackID"), "stackID")
    _reference(value.get("measurementStack"), "measurementStack")
    _reference(value.get("runnerCandidate"), "runnerCandidate")
    _reference(value.get("runnerCertificate"), "runnerCertificate")
    _reference(value.get("appCandidate"), "appCandidate")
    _reference(value.get("appReleaseCandidate"), "appReleaseCandidate")
    return value


def render_swift(candidate: dict[str, Any]) -> str:
    stack = candidate["measurementStack"]
    runner = candidate["runnerCandidate"]
    return f"""// Generated by scripts/generate_power2_candidate_identity.py.
// Edit products/power/candidate.json and regenerate. Do not compile this
// candidate identity into a public App release.

enum Power2CandidateIdentity {{
    static let stackID = "{candidate['stackID']}"
    static let measurementStackPath = "{stack['path']}"
    static let measurementStackSHA256 = "{stack['sha256']}"
    static let runnerCandidateManifestPath = "{runner['path']}"
    static let runnerCandidateManifestSHA256 = "{runner['sha256']}"
    static let publicIntakeOpen = false
    // Enables the closed Official end-to-end rehearsal. GitHub submission
    // remains locked independently by publicIntakeOpen.
    static let appReleaseAvailable = true
}}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of rewriting a stale generated Swift file",
    )
    args = parser.parse_args(argv)
    try:
        expected = render_swift(load_candidate())
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.check:
        try:
            actual = OUTPUT_PATH.read_text(encoding="utf-8")
        except OSError:
            actual = ""
        if actual != expected:
            print(
                "error: apps/ios/Power2CandidateIdentity.generated.swift "
                "is stale",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
