#!/usr/bin/env python3
"""Generate the Swift identity embedded by the Power App.

The generated identity contains only immutable measurement and component
identity. Repository intake state is deliberately not compiled into the App:
trusted CI and the active product pointer remain authoritative.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CANDIDATE_PATH = ROOT / "products/power/candidate.json"
CURRENT_PATH = ROOT / "products/power/current.json"
OUTPUT_PATH = ROOT / "apps/ios/Power2ProductIdentity.generated.swift"


def _string(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{field} must be a non-empty string")
    return value


def _reference(value: Any, field: str) -> dict[str, str]:
    if not isinstance(value, dict):
        raise ValueError(f"{field} must be an object")
    path = _string(value.get("path"), f"{field}.path")
    digest = _string(value.get("sha256"), f"{field}.sha256")
    if len(digest) != 64 or any(
        character not in "0123456789abcdef" for character in digest
    ):
        raise ValueError(f"{field}.sha256 must be a lowercase SHA-256")
    return {"path": path, "sha256": digest}


def load_product_identity() -> dict[str, Any]:
    source_path = CURRENT_PATH if CURRENT_PATH.exists() else CANDIDATE_PATH
    value = json.loads(source_path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("Power product pointer must be a JSON object")
    status = value.get("status")
    if source_path == CURRENT_PATH:
        if (
            value.get("schemaVersion") != "power-stack-pointer-1.0.0"
            or status != "active"
            or value.get("publicIntakeOpen") is not True
        ):
            raise ValueError("unsupported active Power product pointer")
        runner_key = "runnerComponents"
        app_key = "appRelease"
    else:
        if (
            value.get("schemaVersion")
            != "power-stack-pointer-1.0.0-draft.1"
            or status != "migration-draft"
            or value.get("publicIntakeOpen") is not False
            or value.get("appRelease") is not None
        ):
            raise ValueError("unsupported Power migration candidate")
        runner_key = "runnerCandidate"
        app_key = "appReleaseCandidate"
    _string(value.get("stackID"), "stackID")
    _reference(value.get("measurementStack"), "measurementStack")
    _reference(value.get(runner_key), runner_key)
    _reference(value.get("runnerCertificate"), "runnerCertificate")
    _reference(value.get(app_key), app_key)
    value["_runnerReferenceKey"] = runner_key
    return value


def render_swift(pointer: dict[str, Any]) -> str:
    stack = pointer["measurementStack"]
    runner = pointer[pointer["_runnerReferenceKey"]]
    return f"""// Generated by scripts/generate_power2_product_identity.py.
// Edit the Power product pointer and regenerate. Intake state is intentionally
// not embedded; trusted repository CI remains authoritative.

enum Power2ProductIdentity {{
    static let stackID = "{pointer['stackID']}"
    static let measurementStackPath = "{stack['path']}"
    static let measurementStackSHA256 = "{stack['sha256']}"
    static let runnerComponentsManifestPath = "{runner['path']}"
    static let runnerComponentsManifestSHA256 = "{runner['sha256']}"
    // A release candidate may be rehearsed before trusted public intake opens.
    // Repository validation decides whether any produced result is accepted.
    static let appReleaseAvailable = true
}}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of rewriting a stale generated Swift file",
    )
    args = parser.parse_args(argv)
    try:
        expected = render_swift(load_product_identity())
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.check:
        try:
            actual = OUTPUT_PATH.read_text(encoding="utf-8")
        except OSError:
            actual = ""
        if actual != expected:
            print(
                "error: apps/ios/Power2ProductIdentity.generated.swift "
                "is stale",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
