#!/usr/bin/env python3
"""Generate the Swift identity for the exact Power MLX dependency lock."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = ROOT / "apps/PowerRunnerKit/Package.resolved"
OUTPUT_PATH = (
    ROOT
    / "apps/PowerRunnerKit/Sources/PowerMLXRuntime"
    / "PowerMLXDependencyLock.generated.swift"
)
REQUIRED_DIRECT_PINS = {
    "mlx-swift": (
        "0.31.6",
        "0bb916c67f4b9e5c682cbe02a42c701c93ab5021",
    ),
    "mlx-swift-lm": (
        "3.31.4",
        "bd4b7434e6bdb588c7ef55706ff8904cb7fd4c57",
    ),
    "swift-huggingface": (
        "0.9.0",
        "b721959445b617d0bf03910b2b4aced345fd93bf",
    ),
    "swift-transformers": (
        "1.3.0",
        "b38443e44d93eca770f2eb68e2a4d0fa100f9aa2",
    ),
}


def render() -> str:
    lock_bytes = LOCK_PATH.read_bytes()
    document = json.loads(lock_bytes)
    pins = {
        pin["identity"]: (
            pin["state"].get("version"),
            pin["state"]["revision"],
        )
        for pin in document.get("pins", [])
    }
    for identity, expected in REQUIRED_DIRECT_PINS.items():
        if pins.get(identity) != expected:
            raise ValueError(
                f"{identity} resolved to {pins.get(identity)!r}, "
                f"expected {expected!r}"
            )
    digest = hashlib.sha256(lock_bytes).hexdigest()
    return f"""// Generated by scripts/generate_power_mlx_dependency_identity.py.
// Do not edit by hand.

enum PowerMLXDependencyLock {{
    static let sha256 = "{digest}"
}}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of rewriting stale generated Swift",
    )
    args = parser.parse_args(argv)
    try:
        expected = render()
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    if args.check:
        actual = (
            OUTPUT_PATH.read_text(encoding="utf-8")
            if OUTPUT_PATH.exists()
            else ""
        )
        if actual != expected:
            print(
                "error: PowerMLXDependencyLock.generated.swift is stale",
                file=sys.stderr,
            )
            return 1
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
