#!/usr/bin/env python3
"""Generate iOS App release constants from one machine-readable identity."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
IDENTITY_PATH = ROOT / "ios-app/Config/release-identity.json"
XCCONFIG_PATH = ROOT / "ios-app/Config/AppVersion.xcconfig"
SWIFT_PATH = (
    ROOT / "ios-app/BenchmarkApp/AppReleaseIdentity.generated.swift"
)
SCHEMA_VERSION = "ios-benchmark-app-release-identity-1.0"
SEMVER_PATTERN = re.compile(
    r"^[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?$"
)


def _string(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{field} must be a non-empty string")
    return value


def load_identity() -> dict[str, Any]:
    value = json.loads(IDENTITY_PATH.read_text())
    if not isinstance(value, dict):
        raise ValueError("release identity must be a JSON object")
    if value.get("schemaVersion") != SCHEMA_VERSION:
        raise ValueError("unsupported release identity schema")
    app = value.get("app")
    power = value.get("power")
    if not isinstance(app, dict) or not isinstance(power, dict):
        raise ValueError("release identity requires app and power objects")

    app_version = _string(app.get("version"), "app.version")
    app_build = _string(app.get("build"), "app.build")
    if SEMVER_PATTERN.fullmatch(app_version) is None:
        raise ValueError("app.version must be a semantic version")
    if not app_build.isdigit() or int(app_build) < 1:
        raise ValueError("app.build must be a positive integer string")

    semantic_versions = (
        "sourceProtocolVersion",
        "publishedReleaseVersion",
        "minimumRunnerVersion",
    )
    for field in semantic_versions:
        candidate = _string(power.get(field), f"power.{field}")
        if SEMVER_PATTERN.fullmatch(candidate) is None:
            raise ValueError(f"power.{field} must be a semantic version")
    for field in (
        "releaseID",
        "resultSchemaVersion",
        "submissionSchemaVersion",
        "submissionDirectory",
        "runnerID",
    ):
        _string(power.get(field), f"power.{field}")
    if not power["submissionDirectory"].startswith("submissions/suite-b/"):
        raise ValueError("power.submissionDirectory must stay in Suite B")
    if ".." in Path(power["submissionDirectory"]).parts:
        raise ValueError("power.submissionDirectory cannot traverse directories")
    return value


def render_xcconfig(identity: dict[str, Any]) -> str:
    app = identity["app"]
    return (
        "// Generated by scripts/generate_ios_app_release_identity.py.\n"
        "// Edit ios-app/Config/release-identity.json, then regenerate.\n"
        f"MARKETING_VERSION = {app['version']}\n"
        f"CURRENT_PROJECT_VERSION = {app['build']}\n"
    )


def render_swift(identity: dict[str, Any]) -> str:
    app = identity["app"]
    power = identity["power"]
    return f"""// Generated by scripts/generate_ios_app_release_identity.py.
// Edit ios-app/Config/release-identity.json, then regenerate.

enum AppReleaseIdentity {{
    static let appVersion = "{app['version']}"
    static let appBuild = "{app['build']}"
    static let powerReleaseID = "{power['releaseID']}"
    static let powerSourceProtocolVersion = "{power['sourceProtocolVersion']}"
    static let powerResultSchemaVersion =
        "{power['resultSchemaVersion']}"
    static let powerPublishedReleaseVersion = "{power['publishedReleaseVersion']}"
    static let powerSubmissionSchemaVersion =
        "{power['submissionSchemaVersion']}"
    static let powerSubmissionDirectory =
        "{power['submissionDirectory']}"
    static let powerRunnerID = "{power['runnerID']}"
    static let minimumPowerRunnerVersion = "{power['minimumRunnerVersion']}"
}}
"""


def _update(path: Path, expected: str, check: bool) -> bool:
    if check:
        try:
            actual = path.read_text()
        except OSError:
            actual = ""
        if actual != expected:
            print(
                f"error: {path.relative_to(ROOT)} is not generated from "
                f"{IDENTITY_PATH.relative_to(ROOT)}",
                file=sys.stderr,
            )
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected)
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of rewriting stale generated files",
    )
    args = parser.parse_args(argv)
    try:
        identity = load_identity()
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    valid = all(
        (
            _update(XCCONFIG_PATH, render_xcconfig(identity), args.check),
            _update(SWIFT_PATH, render_swift(identity), args.check),
        )
    )
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
