// Generated by scripts/generate_power_mlx_dependency_identity.py.
// Do not edit by hand.

enum PowerMLXDependencyLock {
    static let sha256 = "6dc7774e01f6cd7449d42a1d36655fe61802c832689369e76f0e603ee218e1ef"
}
